books/urls.py
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static 
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('plain/', views.index, name='index1'),
    path('<int:book_id>/', views.book_detail, name='book_detail'),
    
    path('authors/', views.authors, name='authors_index'),
    path('author/<int:author_id>/', views.author_detail, name='author_detail'),
    path('authors/paginated_list', views.authors_paginated_list, name='authors_paginated_list'),
    
    path('genres/', views.genres, name='genres_index'),
    path('d3graph/', views.d3graph, name='d3graph'),
    path('d3graph/json_data_sender', views.json_data_sender, name='json_data_sender'),
]

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compositions/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('score/<int:score_id>/', views.score, name='score'),
    path('i18n/', include('django.conf.urls.i18n')),
    
]

oudwithrad/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, re_path
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.views.static import serve

admin.autodiscover()

urlpatterns = i18n_patterns(
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)
#urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns = [
        #re_path(r'^filer/', include('filer.urls')),
        re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns
# note the django CMS URLs included via i18n_patterns

urlpatterns += i18n_patterns(
    
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^polls/', include('polls.urls')),
    #re_path(r'^compositions/', include('compositions.urls')),
    re_path(r'^', include('cms.urls')),
)

compositions/models.py
from django.db import models
from django.utils.html import mark_safe
from cms.models.fields import PlaceholderField

# Create your models here.

class Composer(models.Model):
  monthes = [(1, "January"),(2, "Febraury"),(3, "March"),(4, "April"),(5, "May"),(6, "June"),(7, "July"),(8, "August"),(9, "September"),(10, "October"),(11, "November"),(12, "December"),]
  
  days = [(1, "1"),(2, "2"),(3, "3"),(4, "4"),(5, "5"),(6, "6"),(7, "7"),(8, "8"),(9, "9"),(10, "10"),(11, "11"),(12, "12"),(13, "13"),(14, "14"),(15, "15"),(16, "16"),(17, "17"),(18, "18"),(19, "19"),(20, "20"),(21, "21"),(22, "22"),(23, "23"),(24, "24"),(25, "25"),(26, "26"),(27, "27"),(28, "28"),(29, "29"),(30, "30"),(31, "31"),]
  
  composer_first_name_en = models.CharField(max_length=50, blank=True)
  composer_first_name_ar = models.CharField(max_length=50, blank=True)
  composer_middle_name_en = models.CharField(max_length=50, blank=True)
  composer_middle_name_ar = models.CharField(max_length=50, blank=True)
  composer_last_name_en = models.CharField(max_length=50)
  composer_last_name_ar = models.CharField(max_length=50)
  arabic_definite_article = models.BooleanField(default=False, blank=True, null=True,)
  composer_birth_city_en = models.CharField(max_length=50, blank=True)
  composer_birth_city_ar = models.CharField(max_length=50, blank=True)
  composer_birth_locality_en = models.CharField(max_length=50, blank=True)
  composer_birth_locality_ar = models.CharField(max_length=50, blank=True)
  composer_birth_country_en = models.CharField(max_length=50, blank=True)
  composer_birth_country_ar = models.CharField(max_length=50, blank=True)
  
  composer_birth_year = models.SmallIntegerField(blank=True, null=True)
  composer_birth_month = models.SmallIntegerField(choices=monthes, blank=True, null=True)
  composer_birth_day = models.SmallIntegerField(choices=days,blank=True, null=True)
  
  composer_death_year = models.SmallIntegerField(blank=True, null=True)
  composer_death_month = models.SmallIntegerField(choices=monthes, blank=True, null=True)
  composer_death_day = models.SmallIntegerField(choices=days,blank=True, null=True)
  
  def __str__(self):
        return self.composer_last_name_en

    
class ComposerImage(models.Model):
  composer = models.ForeignKey(Composer, on_delete=models.CASCADE)
  composer_image = models.ImageField(upload_to='compositions/composers/images/')
  profile_image = models.BooleanField(default=False)
  image_description_en = models.CharField(max_length=150)
  image_description_ar = models.CharField(max_length=150)
  
  def image_tag(self):
        if self.composer_image:
            return mark_safe('<img src="%s" style="width: 150px; height:150px;" />' % self.composer_image.url)
        else:
            return 'No Image Found'
  image_tag.short_description = 'Composer Image'
  
  def save(self, *args, **kwargs):
        if self.profile_image:
            try:
                temp = ComposerImage.objects.filter(composer=self.composer).get(profile_image=True)
                if self != temp:
                    temp.profile_image = False
                    temp.save()
            except ComposerImage.DoesNotExist:
                pass
        super(ComposerImage, self).save(*args, **kwargs)
  
  def __str__(self):
        return mark_safe('<img src="%s" style="width: 150px; height:150px;" />' % self.composer_image.url)

class Composition(models.Model):
  class Meta:
        ordering = ['year']
  title_en = models.CharField(max_length=150)
  title_ar = models.CharField(max_length=150)
  composer = models.ForeignKey(Composer, on_delete=models.CASCADE)
  year = models.SmallIntegerField(blank=True, null=True)
  
  def __str__(self):
        return self.title_en + ' - ' + self.composer.composer_last_name_en

class Rhythm(models.Model):
  rhythm_en = models.CharField(max_length=50, blank=True, null=True)
  rhythm_ar = models.CharField(max_length=50, blank=True, null=True)
  rhythm_svg = models.FileField(upload_to='compositions/rhythms/')
  
  def __str__(self):
        return self.rhythm_en
      
class Score(models.Model):
  composition = models.ForeignKey(Composition, on_delete=models.CASCADE) 
  maqam_en = models.CharField(max_length=50, blank=True, null=True)
  maqam_ar = models.CharField(max_length=50, blank=True, null=True)
  rhythm_en = models.CharField(max_length=50, blank=True, null=True)
  rhythm_ar = models.CharField(max_length=50, blank=True, null=True)
  rhythm = models.ForeignKey(Rhythm, on_delete=models.CASCADE, blank=True, null=True)
  #abc_score = models.FileField(upload_to='compositions/scores/')
  abc_score_text = models.TextField()
  notation_source_en = models.CharField(max_length=50, blank=True, null=True)
  notation_source_ar = models.CharField(max_length=50, blank=True, null=True)
  #Comment = PlaceholderField('comment')
  
  def __str__(self):
        return self.composition.title_en + ' - ' + self.notation_source_en

compositions/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils.translation import gettext as _



from .models import Composer, Composition, Score, ComposerImage
# Create your views here.



def index(request):
  #composers_count = Composer.objects.count()
  #compositions_count = Composition.objects.count()
  #scores_count = Score.objects.count()
  
  #composers = Composer.objects.prefetch_related('ComposerImage', 'Composition', 'Score' ).all
  composers  = Composer.objects.order_by('composer_last_name_en')
  composers_count = Composer.objects.count()
  
  #profile_images = ComposerImage.objects.filter(profile_image=True)
  return render(request, 'compositions/index.html', {'composers': composers, 'composers_count': composers_count,})
  #return HttpResponse(_("Hello, world. The database has {0} composers, {1} compositions, and {2} scores. ".format(composers_count, compositions_count, scores_count)))
  
def score(request, score_id):
  try:
    score = Score.objects.get(pk=score_id)
    composition = Composition.objects.get(score__pk=score_id)
    composer = Composer.objects.get(composition__pk=composition.pk)
    
  except Score.DoesNotExist:
    raise Http404("Score does not exist")
  return render(request, 'compositions/score.html', {'score': score, 'composer': composer, 'composition': composition})

compositions/templates/compositions/compositions_base.html
{% extends "base.html" %}
{% load cms_tags menu_tags sekizai_tags %}


{% block css %}
  <style>
    h4 {color: #f57900;}
    a {color: #007CF5;}
    a:hover {color: #f57900;}
    .composer_name {border-bottom: 1px solid rgba(33, 47, 31, .25);}
    //old orage color: #f57900
    .composer_lifespan {color:#000; font-size: 18px;}
    .images_link {}
  </style>
{% endblock css%}

{% block content %}

{% endblock %}

compositions/templates/compositions/index.html
{% extends "compositions/compositions_base.html" %}
{% load arabic_numbers %}

{% block title %}Compositions | Home{% endblock title %}

{% block content %}
<!--Arabic-->


{% if LANGUAGE_CODE == 'ar' %}
<div class="container" dir=rtl>
  <div class="row">
    <div class="col-12">
      <h1>مرحبا بكم في قاعدة بيانات مقطوعات العود</h1>
      
      <hr>
      
      <p>
  يوجد {{composers_count|enToArNumb}} مؤلف في قاعدة البيانات.
      </p>
      
      <p>
  المؤلفون مرتبون هجائيا بحسب اسم العائلة.
      </p>
      
      {% for composer in composers %}
      <div class="card text-bg-dark text-center mb-3" style="max-width: 18rem;">
      
      {% for image in composer.composerimage_set.all %}
        {% if image.profile_image == True%}
        <a href='#composer_{{composer.id}}'>
          <img src="{{ image.composer_image.url}}" class="card-img-top" alt="...">
        </a>
        {% else %}
        
        {%endif%}
      {% endfor %}
      
        <div class="card-body">
          <h5 class="card-title">
            {{composer.composer_first_name_ar }} 
            {% if composer.arabic_definite_article %}ال{%endif%}{{ composer.composer_last_name_ar }}
          </h5>
          <p class="card-text">
            {{ composer.composer_birth_country_ar }}
            {% if composer.composer_death_year %}
              ({{ composer.composer_birth_year|enToArNumb }} - {{ composer.composer_death_year|enToArNumb }})
            {% else %}
              ({{ composer.composer_birth_year|enToArNumb }} - )
            {% endif %}
          </p>
        </div>
        
        <div class="card-footer bg-transparent">
          {% if  composer.composition_set.count == 1 %}
      (مقطوعة واحدة)
          {% elif composer.composition_set.count == 2 %}
      (مقطوعتين)
          {% elif composer.composition_set.count == 0 %}
      (لا يوجد مقطوعات)
          {% else %}
          ({{ composer.composition_set.count|enToArNumb }} مقطوعات).
          {% endif %}
        </div>
      </div>
      {% endfor %}
      
      
      
  
      {% for composer in composers|dictsort:"composer_last_name_ar" %}
      <h2 class="composer_name" id='composer_{{ composer.id }}'>{{ composer.composer_first_name_ar }} 
        {% if composer.arabic_definite_article %}ال{%endif%}{{ composer.composer_last_name_ar }}
      </h2>
    
      <ul>
      {% for composition in composer.composition_set.all %}
        <li>{{ composition.title_ar }}{% if composition.year %} ({{ composition.year }}){% endif %}.</li>
        <ul>
          {% for score in composition.score_set.all %}
          <li>
            <a href="score/{{ score.id }}/">
        تدوينة موسيقية مصدرها: 
            </a>
            {{ score.notation_source_ar }}
          </li>
          {% endfor %}
        </ul>
      {% endfor %}
      </ul>
      {% endfor %}
    </div>
  </div>
</div>

  
  
<!--English-->
{% else %}

<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Music Scores of Compositions for Oud</h1>
      <hr>
      <p>We currently have {{composers_count}} composers in the Database.</p>
      <P>The composers are arranged alpabetacally according to their family names.</p>
      
      {% for composer in composers %}
      <div class="card text-bg-dark text-center mb-3" style="max-width: 18rem;">
      
      {% for image in composer.composerimage_set.all %}
        {% if image.profile_image == True%}
        <a href='#composer_{{composer.id}}'>
          <img src="{{ image.composer_image.url}}" class="card-img-top" alt="...">
        </a>
        {% else %}
        
        {%endif%}
      {% endfor %}
      
        <div class="card-body">
          <h5 class="card-title">
            {{composer.composer_first_name_en }} 
            {% if composer.arabic_definite_article %}Al-{%endif%}{{ composer.composer_last_name_en }}
          </h5>
          <p class="card-text">
            {{ composer.composer_birth_country_en }}
            {% if composer.composer_death_year %}
              ({{ composer.composer_birth_year }} - {{ composer.composer_death_year }})
            {% else %}
              ({{ composer.composer_birth_year }} - )
            {% endif %}
          </p>
        </div>
        
        <div class="card-footer bg-transparent">
          {% if composer.composition_set.count > 0 %}
          {% if  composer.composition_set.count == 1 %}
          (1 composition)
          {% else %}
          ({{ composer.composition_set.count }} compositions)
          {% endif %}
          {% else %}
          (0 compositions)
          {% endif %}
        </div>
      </div>
      {% endfor %}
      
      
  
      {% for composer in composers %}
      <h2 class="composer_name" id='composer_{{composer.id}}'>
        {{ composer.composer_first_name_en }}
        {% if composer.arabic_definite_article %}al-{%endif%}{{ composer.composer_last_name_en }}
      </h2>
  
      {% for image in composer.composerimage_set.all %}
      {% if image.profile_image == True%}
      <p><img src="{{ image.composer_image.url}}" style="border: 1px solid #f57900;border-radius: 4px;padding: 5px;width: 150px;"></p>
      {%endif%}
      {% endfor %}  
  

    
      <ul>
        {% for composition in composer.composition_set.all %}
        <li>{{ composition.title_en }}{% if composition.year %} ({{ composition.year }}){% endif %}.</li>
          <ul>
            {% for score in composition.score_set.all %}
            <li>
              <a href="score/{{ score.id }}/">a music score by:  </a>
              {{ score.notation_source_en }}
            </li>
            {% endfor %}
          </ul>
        {% endfor %}
      </ul>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

compositions/templates/compositions/score.html
{% extends "compositions/compositions_base.html" %}
{% load cms_tags menu_tags sekizai_tags %}
{% load cms_tags %}
{% load abc_extras %}
{% load static %}

<!-- Title -->
{% block title %}
  {% if LANGUAGE_CODE == 'ar' %}
  المقطوعات | {{ composition.title_ar }}
  {% else %}
    Compositions | {{ composition.title_en }}
  {% endif %}
{% endblock title %}


<!-- content -->
{% block content %}

<!-- arabic content -->
{% if LANGUAGE_CODE == 'ar' %}

<div class="container" dir=rtl>
  <div class="row">
    <div class="col-12">
    
      <h1>{{ composition.title_ar }} {% if composition.year %} ({{ composition.year }}){% endif %}</h1>
      <h4 class="composer_name">المؤلف:
        {{ composer.composer_first_name_ar }} 
        {% if composer.arabic_definite_article %}ال{%endif%}{{ composer.composer_last_name_ar }}
        <span class="composer_lifespan">
          {{ composer.composer_birth_country_ar }}
          {% if composer.composer_death_year %}
            ({{ composer.composer_birth_year }} - {{ composer.composer_death_year }})
          {% else %}
            ({{ composer.composer_birth_year }} - )
          {% endif %}
        </span>
      </h4>
          
      {% if score.maqam_ar %}
        <p>المقام: [{{ score.maqam_ar }}]<p>
      {% endif %}
      
      {% if score.rhythm %}
        <p>الإيقاع: [{{ score.rhythm.rhythm_ar }}]<p>
        <p align=center><img class="img-fluid" src="{{ score.rhythm.rhythm_svg.url }}"></p>
      {% endif %}
          
      <p><a href='/library/music-scores/#{{ composer.composer_last_name_en }}'><< العودة لفهرس المقطوعات</a></p>
      <p>بإمكانك الاستماع لموسيقى هذه التدوينة منتجة بشكل آلي من قبل الموقع من خلال الضغط في أي مكان داخل التدوينة ولإيقاف الموسيقى عليك الضغط على أي مكان خارج التدوينة.<br>
    ملاحظة: الصوت المنتج آليا لا يحتوى على النغمات الشرقية ذات الربع التون.</p>


    </div>
  </div>
    
  <div class="row">
    <div class="col-12">
      <div dir="ltr" class="abc">
{{ score.abc_score_text }}
      </div>
      <p>التدوينة الموسيقية من قبل: {{ score.notation_source_ar }} </p>
    </div>
  </div>
  
  <div class="row">
    <div class="col-12">
      <div id="comp" class="dlog">wait until soundfonts are loaded ...<br></div>
    </div>
  </div>
  
</div>

  
<!-- english content -->  
{% else %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>
        {{ composition.title_en }} {% if composition.year %} ({{ composition.year }}){% endif %}
      </h1>
      <h4 class="composer_name">Composer: {{ composer.composer_first_name_en }} 
        {% if composer.arabic_definite_article %}al-{%endif%}{{ composer.composer_last_name_en }}
        <span class="composer_lifespan">
          {{ composer.composer_birth_country_en }}
          {% if composer.composer_death_year %}
            ({{ composer.composer_birth_year }} - {{ composer.composer_death_year }})
          {% else %}
            ({{ composer.composer_birth_year }} - )
          {% endif %}
        </span>
      </h4>
  
      <p><a href='/library/music-scores/#{{ composer.composer_last_name_en }}'><< Back to Compositions Index</a></p>
      <p>
        You can listen to a crude auto genetrated sound file of this score by: clicking or pressing anyhwere inside the score, to stop the playback: click anywhere outside the score.<br>
        Note: the autogenerated sound file doesn't yet contain quarter tone pitches.
      </p>
    </div>
  </div>
    
  <div class="row">
    <div class="col-12">
      <div dir="ltr" class="abc">
{{ score.abc_score_text }}
      </div>
      <p>Notation by: {{ score.notation_source_en }} </p>
    </div>
  </div>
  
  <div class="row">
    <div class="col-12">
      <div id="comp" class="dlog">wait until soundfonts are loaded ...<br></div>
    </div>
  </div>
  
</div>
{% endif %}





{% endblock content %}

      
      {% block js %}
        <script src="{% static 'oudwithrad/js/abc2svg-1.js' %}"></script>
        <script src="{% static 'oudwithrad/js/xmlplay_emb.js' %}"></script>
      {% endblock js %}