books/urls.py
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static 
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('plain/', views.index, name='index1'),
    path('<int:book_id>/', views.book_detail, name='book_detail'),
    
    path('authors/', views.authors, name='authors_index'),
    path('author/<int:author_id>/', views.author_detail, name='author_detail'),
    path('authors/paginated_list', views.authors_paginated_list, name='authors_paginated_list'),
    
    path('genres/', views.genres, name='genres_index'),
    path('d3graph/', views.d3graph, name='d3graph'),
    path('d3graph/json_data_sender', views.json_data_sender, name='json_data_sender'),
]

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manuscripts/urls.py
from django.urls import path, include

from . import views

app_name = 'manuscripts'

urlpatterns = [
    path('', views.index, name='index'),
    path('manuscript/<int:manuscript_id>/', views.manuscript, name='manuscript'),
    
]

oudwithrad/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, re_path
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.views.static import serve

admin.autodiscover()

urlpatterns = i18n_patterns(
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)
#urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns = [
        #re_path(r'^filer/', include('filer.urls')),
        re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns
# note the django CMS URLs included via i18n_patterns

urlpatterns += i18n_patterns(
    
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^polls/', include('polls.urls')),
    #re_path(r'^compositions/', include('compositions.urls')),
    re_path(r'^', include('cms.urls')),
)

manuscripts/models.py
from django.db import models
from django.utils.translation import get_language
from django.utils.translation import ugettext_lazy as _
from cms.models.fields import PlaceholderField
#from cms.models import Page as cmsPage

# Create your models here.

class Author(models.Model):
  monthes = [(1, "January"),(2, "Febraury"),(3, "March"),(4, "April"),(5, "May"),(6, "June"),(7, "July"),(8, "August"),(9, "September"),(10, "October"),(11, "November"),(12, "December"),]
  
  days = [(1, "1"),(2, "2"),(3, "3"),(4, "4"),(5, "5"),(6, "6"),(7, "7"),(8, "8"),(9, "9"),(10, "10"),(11, "11"),(12, "12"),(13, "13"),(14, "14"),(15, "15"),(16, "16"),(17, "17"),(18, "18"),(19, "19"),(20, "20"),(21, "21"),(22, "22"),(23, "23"),(24, "24"),(25, "25"),(26, "26"),(27, "27"),(28, "28"),(29, "29"),(30, "30"),(31, "31"),]
  
  first_name_ar = models.CharField(max_length=150, blank=True)
  middle_name_ar = models.CharField(max_length=150, blank=True)
  last_name_ar = models.CharField(max_length=150)
  
  first_name_en = models.CharField(max_length=150, blank=True)
  middle_name_en = models.CharField(max_length=150, blank=True)
  last_name_en = models.CharField(max_length=150)
  
  arabic_definite_article = models.BooleanField(default=False, blank=True, null=True,)
  
  
  birth_city_ar = models.CharField(verbose_name=_('Birth City AR'), max_length=50, blank=True)
  birth_locality_ar = models.CharField(verbose_name=_('Birth Locality AR'), max_length=50, blank=True)
  birth_country_ar = models.CharField(verbose_name=_('Birth Country AR'), max_length=50, blank=True)
  
  birth_city_en = models.CharField(verbose_name=_('Birth City EN'), max_length=50, blank=True)
  birth_locality_en = models.CharField(verbose_name=_('Birth Locality EN'), max_length=50, blank=True)
  birth_country_en = models.CharField(verbose_name=_('Birth Country EN'), max_length=50, blank=True)
  
  birth_year_CE = models.SmallIntegerField(verbose_name=_('Birth Year CE'), blank=True, null=True)
  birth_month_CE = models.SmallIntegerField(verbose_name=_('Birth Month CE'), choices=monthes, blank=True, null=True)
  birth_day_CE = models.SmallIntegerField(verbose_name=_('Birth Day CE'), choices=days,blank=True, null=True)
  
  birth_year_AH = models.SmallIntegerField(verbose_name=_('Birth Year AH'), blank=True, null=True)
  birth_month_AH = models.SmallIntegerField(verbose_name=_('Birth Month AH'), choices=monthes, blank=True, null=True)
  birth_day_AH = models.SmallIntegerField(verbose_name=_('Birth Day AH'), choices=days,blank=True, null=True)
  
  death_year_CE = models.SmallIntegerField(verbose_name=_('Death Year CE'), blank=True, null=True)
  death_month_CE = models.SmallIntegerField(verbose_name=_('Death Month CE'), choices=monthes, blank=True, null=True)
  death_day_CE = models.SmallIntegerField(verbose_name=_('Death Day CE'), choices=days,blank=True, null=True)
  
  death_year_AH = models.SmallIntegerField(verbose_name=_('Death Year AH'), blank=True, null=True)
  death_month_AH = models.SmallIntegerField(verbose_name=_('Death Month AH'), choices=monthes, blank=True, null=True)
  death_day_AH = models.SmallIntegerField(verbose_name=_('Death Month AH'), choices=days,blank=True, null=True)
  
  class Meta:
    verbose_name = _('Author')
    verbose_name_plural = _('Authors')
  
  def __str__(self):
    if get_language() == 'ar':
      return self.first_name_ar + ' ' + self.last_name_ar
    else:
      return self.first_name_en + ' ' + self.last_name_en
    
class Title(models.Model):
  author = models.ForeignKey(Author, on_delete=models.CASCADE)
  arabic_name = models.CharField(max_length=250, blank=True)
  english_translated_name = models.CharField(max_length=250, blank=True)
  english_transliterated_name = models.CharField(max_length=250, blank=True)
  #cms_page = models.ForeignKey(cmsPage, related_name='title_cmsPage', on_delete=models.CASCADE, null=True, blank=True)
  def __str__(self):
    return self.arabic_name

class Manuscript(models.Model):
  title = models.ForeignKey(Title, on_delete=models.PROTECT)
  location = models.CharField(max_length=150, blank=True)
  call_number= models.CharField(max_length=150, blank=True)
  #cms_page = models.ForeignKey(cmsPage, related_name='manuscript_cmsPage', on_delete=models.CASCADE, null=True, blank=True)
  #aquisition_date = 
  acquisition_details = models.CharField(max_length=250, blank=True)
  arabic_copier_name = models.CharField(max_length=250, blank=True)
  english_copier_name = models.CharField(max_length=250, blank=True)
  def __str__(self):
    return self.call_number

class Folio(models.Model):
  title = models.ForeignKey(Title, on_delete=models.PROTECT)
  call_number= models.ForeignKey(Manuscript, on_delete=models.PROTECT)
  file_name = models.CharField(max_length=250, blank=True)
  page_index = models.IntegerField(blank=True, null=True)
  transcription = models.TextField(blank=True, null=True)
  def __str__(self):
    return self.file_name

manuscripts/views.py
from django.shortcuts import render
from . models import Author, Title, Manuscript, Folio
# Create your views here.
def index(request):
  titles = Title.objects.all()
  titles_count = Title.objects.count()
  manuscripts_count = Manuscript.objects.count()
  folio_count = Folio.objects.count()
  context = {'titles': titles,
             'titles_count': titles_count,
             'manuscripts_count': manuscripts_count,
             'folio_count': folio_count,
             }
  return render(request, 'manuscripts/index.html', context)

def manuscript(request, manuscript_id):
  manuscript = Manuscript.objects.get(pk=manuscript_id)
  print(manuscript)
  context = {'manuscript':manuscript,}
  return render(request, 'manuscripts/manuscript_detail.html', context)

manuscripts/templates/manuscripts/index.html
{% extends "base.html" %}
{% load arabic_numbers %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block css %}
<style>

  {% if LANGUAGE_CODE == 'ar' %}
  
  ol {list-style-type: arabic-indic; !important}
  
  {% endif %}
  
</style>
{% endblock css %}

{% block title %}NafColl Books{% endblock %}


  <!-- Navigation -->

  <!-- Page Content -->

  {% block content %}
  
  {% if LANGUAGE_CODE == 'ar' %} <!-- start of arabic template -->
  <div class="container">
  
    <div class="row">
      <div class="col-12 p-3">
      
        <h1 class="text-center">أهلا بكم في مجموعة المخطوطات</h1>
        
        <hr style="max-width:650px" class="mx-auto">
        
        <p class="text-center">يوجد حاليا {{ manuscripts_count|enToArNumb }} مخطوط في قاعدة البيانات</a>.</p>
        
        <hr style="max-width:650px" class="mx-auto">
      </div>
    </div>
    
    <div class="row">
      <div class="col-12 p-3">
        
        <ol>
        
        {% for title in titles %}
        
          <li>{{title.arabic_name}}</li>
          
          <ol>
          {% for manuscript in title.manuscript_set.all%}
            <li>
              <a href="{% url 'manuscripts:manuscript' manuscript.id %}">مخطوط {{manuscript.call_number|upper}}</a>
              ({{manuscript.folio_set.count}} صحف).
            </li>
          {% endfor%}
          </ol>
          
        {% endfor %}
        
        </ol>
      
      </div>
    </div>
    
  </div>
  
  {% else %} <!-- start of english template -->
  <div class="container">
  
    <div class="row">
      <div class="col-12 p-3">
      
        <h1 class="text-center">Welcome to the Manuscripts Collection</h1>
        
        <hr style="max-width:650px" class="mx-auto">
        
        <p class="text-center">There are {{ manuscripts_count }} manuscripts in the database</a>.</p>
        
        <hr style="max-width:650px" class="mx-auto">
      </div>
    </div>
    
    <div class="row">
      <div class="col-12 p-3">
        
        <ol>
        
        {% for title in titles %}
        
          <li>{{title.english_translated_name}}</li>
          
          <ol>
          {% for manuscript in title.manuscript_set.all%}
            <li>
              <a href="{% url 'manuscripts:manuscript' manuscript.id %}">{{manuscript.call_number|upper}}</a>
              ({{manuscript.folio_set.count}} folios).
            </li>
          {% endfor%}
          </ol>
          
        {% endfor %}
        
        </ol>
      
      </div>
    </div>
    
  </div>
  
  {% endif %}
  
  {% endblock content %}

manuscripts/templates/manuscripts/manuscript_detail.html
{% extends "base.html" %}
{% load arabic_numbers %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load static %}

{% block css %}
<style>

  {% if LANGUAGE_CODE == 'ar' %}
  
  ol {list-style-type: arabic-indic; !important}
  
  {% endif %}
  
</style>
{% endblock css %}

{% block title %}NafColl Books{% endblock %}


  <!-- Navigation -->

  <!-- Page Content -->

  {% block content %}
  
  {% if LANGUAGE_CODE == 'ar' %} <!-- start of arabic template -->
  <div class="container">
  
    <div class="row">
      <div class="col-12 p-3">
      
      <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">الرئيسية</a></li>
            <li class="breadcrumb-item"><a href="{%url 'manuscripts:index' %}">المخطوطات</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{manuscript.title.arabic_name}} من مخطوط {{manuscript.call_number|upper}}</li>
          </ol>
        </nav>
        
        <hr>
      
      <h1 class="text-center">{{manuscript.title.arabic_name}} من مخطوط {{manuscript.call_number|upper}}</h1>
      
      <hr style="max-width:75%;" class="mx-auto">
      
      <div id="current_folio" class="p-3">الصحيفة الحالية 1 من {{manuscript.folio_set.count}}</div>
      
      <div id="openseadragon1" style="height: 500px;" class="col-lg-8 col-md-10 col-sm-12 border mx-auto m-3" dir="ltr"></div>
      
      <div id="transcription" dir="rtl"><h2>تفريغ الصحيفة: </h2>{{manuscript.folio_set.first.transcription|safe}}</div>
      
      </div>
    </div>
    
  </div>
  
  <script src="{% static 'manuscripts/assets/js/openseadragon-bin-3.0.0/openseadragon.min.js'%}"></script>

  <script type="text/javascript">
    var viewer = OpenSeadragon({
      id: "openseadragon1",
      prefixUrl: "{% static 'manuscripts/assets/js/openseadragon-bin-3.0.0/images/' %}",
      tileSources: [
        {% for folio in manuscript.folio_set.all|dictsort:"page_index" %}
        {% with 'manuscripts/deepzoom/'|add:manuscript.call_number|add:'/'|add:folio.file_name as image_static %}
        '{% static image_static %}', 
        {% endwith %}
        {% endfor %}],
      sequenceMode: true,
    });
    
    var transcriptions = {};
    var folio_count = {{manuscript.folio_set.count}};
    
    {% for folio in manuscript.folio_set.all %}
    transcriptions[{{folio.page_index}}] = '{% filter escapejs %}{{folio.transcription|safe}}{% endfilter %}';
    {% endfor %}
    
    //document.getElementById("openseadragon1").addEventListener("page", displayTrans);
    viewer.addHandler('page', functionName);
    function functionName(page) {
      current_folio = document.getElementById("current_folio");
      current_folio.innerHTML = "";
      current_folio.innerHTML = "الصحيفة الحالية: " + (page.page + 1) + ' من ' + folio_count;
      mydiv = document.getElementById("transcription");
      mydiv.innerHTML = "";
      mydiv.innerHTML = "<h2>تفريغ الصحيفة: </h2>" + transcriptions[page.page+1];
      console.log(page.page+1);
      console.log(transcriptions[page.page+1]);
      console.log(transcriptions);
    };
  </script>
  
  {% else %}
  
  <div class="container">
  
    <div class="row">
      <div class="col-12 p-3">
      
      <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">HOME</a></li>
            <li class="breadcrumb-item"><a href="{%url 'manuscripts:index' %}">MANUSCRIPTS</a></li>
            <li class="breadcrumb-item active" aria-current="page">
            {{manuscript.title.english_translated_name}} from the Manuscript {{manuscript.call_number|upper}}
            </li>
          </ol>
        </nav>
        
        <hr>
      
      <h1 class="text-center">{{manuscript.title.english_translated_name}} from the Manuscript {{manuscript.call_number|upper}}</h1>
      
      <hr style="max-width:75%;" class="mx-auto">
      
      <div id="current_folio" class="p-3">Current Folio : 1 of {{manuscript.folio_set.count}}</div>
      
      <div id="openseadragon1" style="height: 500px;" class="col-lg-8 col-md-10 col-sm-12 border mx-auto m-3" dir="ltr"></div>
      
      <div id="transcription"><h2>Folio Transcription: </h2><div dir='rtl'>{{manuscript.folio_set.first.transcription|safe}}</div></div>
      
      </div>
    </div>
    
  </div>
  
  <script src="{% static 'manuscripts/assets/js/openseadragon-bin-3.0.0/openseadragon.min.js'%}"></script>

  <script type="text/javascript">
    var viewer = OpenSeadragon({
      id: "openseadragon1",
      prefixUrl: "{% static 'manuscripts/assets/js/openseadragon-bin-3.0.0/images/' %}",
      tileSources: [
        {% for folio in manuscript.folio_set.all|dictsort:"page_index" %}
        {% with 'manuscripts/deepzoom/'|add:manuscript.call_number|add:'/'|add:folio.file_name as image_static %}
        '{% static image_static %}', 
        {% endwith %}
        {% endfor %}],
      sequenceMode: true,
    });
    
    var transcriptions = {};
    var folio_count = {{manuscript.folio_set.count}};
    
    {% for folio in manuscript.folio_set.all %}
    transcriptions[{{folio.page_index}}] = '{% filter escapejs %}{{folio.transcription|safe}}{% endfilter %}';
    {% endfor %}
    
    //document.getElementById("openseadragon1").addEventListener("page", displayTrans);
    viewer.addHandler('page', functionName);
    function functionName(page) {
      current_folio = document.getElementById("current_folio");
      current_folio.innerHTML = "";
      current_folio.innerHTML = "Current Folio : " + (page.page + 1) + ' of ' + folio_count;
      mydiv = document.getElementById("transcription");
      mydiv.innerHTML = "";
      mydiv.innerHTML = "<h2 dir=ltr>Folio Transcription: </h2><div dir='rtl'>" + transcriptions[page.page+1] +'</div>';
      console.log(page.page+1);
      console.log(transcriptions[page.page+1]);
      console.log(transcriptions);
    };
  </script>
  
  {% endif %}
  
  {% endblock %}