books/urls.py
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static 
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('plain/', views.index, name='index1'),
    path('<int:book_id>/', views.book_detail, name='book_detail'),
    
    path('authors/', views.authors, name='authors_index'),
    path('author/<int:author_id>/', views.author_detail, name='author_detail'),
    path('authors/paginated_list', views.authors_paginated_list, name='authors_paginated_list'),
    
    path('genres/', views.genres, name='genres_index'),
    path('d3graph/', views.d3graph, name='d3graph'),
    path('d3graph/json_data_sender', views.json_data_sender, name='json_data_sender'),
]

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'),
    path('course/<int:course_id>/', views.course, name='course'),
    path('lesson/<int:lesson_id>/', views.lesson, name='lesson'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

oudwithrad/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, re_path
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.views.static import serve

admin.autodiscover()

urlpatterns = i18n_patterns(
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)
#urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns = [
        #re_path(r'^filer/', include('filer.urls')),
        re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns
# note the django CMS URLs included via i18n_patterns

urlpatterns += i18n_patterns(
    
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^polls/', include('polls.urls')),
    #re_path(r'^compositions/', include('compositions.urls')),
    re_path(r'^', include('cms.urls')),
)

courses/models.py
from django.db import models
from django.utils.translation import get_language
from django.utils.translation import ugettext_lazy as _
from cms.models.fields import PlaceholderField

# Create your models here.
class Catagory(models.Model):
  name_en = models.CharField(verbose_name=_('Name en'), max_length=200)
  name_ar = models.CharField(verbose_name=_('Name ar'), max_length=200)
  
  class Meta:
    verbose_name = _('Catagory')
    verbose_name_plural = _('Catagories')
  
  def __str__(self):
    if get_language() == 'ar':
      return self.name_ar
    else:
      return self.name_en
      
class Course(models.Model):
  catagory = models.ForeignKey(Catagory, on_delete=models.CASCADE, verbose_name=_('Catagory'), )
  name_en = models.CharField(verbose_name=_('Name en'), max_length=200)
  name_ar = models.CharField(verbose_name=_('Name ar'), max_length=200)
  
  class Meta:
    verbose_name = _('Course')
    verbose_name_plural = _('Courses')
  
  def __str__(self):
    if get_language() == 'ar':
      return self.catagory.name_ar + ' - ' + self.name_ar
    else:
      return self.catagory.name_en + ' - ' + self.name_en

def lesson_placeholder_slotname(instance):
    return 'lesson_placeholder'

class Lesson(models.Model):
  course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=_('Course'), )
  name_en = models.CharField(verbose_name=_('Name en'), max_length=200)
  name_ar = models.CharField(verbose_name=_('Name ar'), max_length=200)
  video_link = models.URLField(verbose_name=_('Video Link'), max_length = 200)
  lesson_placeholder = PlaceholderField('lesson_placeholder')
  lesson_order = models.IntegerField(verbose_name=_('Lesson Order'), blank=True, null=True,)
  class Meta:
    verbose_name = _('Lesson')
    verbose_name_plural = _('Lessons')
  
  def __str__(self):
    if get_language() == 'ar':
      return self.course.catagory.name_ar + ' - ' + self.course.name_ar + ' - ' + self.name_ar
    else:
      return self.course.catagory.name_en + ' - ' + self.course.name_en + ' - ' + self.name_en


class Question(models.Model):
  lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
  question_text_en = models.CharField(verbose_name=_('Question Text en'), max_length=200)
  question_text_ar = models.CharField(verbose_name=_('Question Text ar'), max_length=200)
  
  class Meta:
    verbose_name = _('Question')
    verbose_name_plural = _('Questions')
  
  def __str__(self):
    if get_language() == 'ar':
      return self.question_text_ar
    else:
      return self.question_text_en
    
class Answer(models.Model):
  answer_text_en = models.CharField(verbose_name=_('Answer Text en'), max_length=200)
  answer_text_ar = models.CharField(verbose_name=_('Answer Text ar'), max_length=200)
  question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name=_('Question'), )
  is_correct = models.BooleanField(verbose_name=_('Is Correct?'))
  
  class Meta:
    verbose_name = _('Answer')
    verbose_name_plural = _('Answers')
  
  def __str__(self):
    if get_language() == 'ar':
      return self.answer_text_ar
    else:
      return self.answer_text_en

courses/views.py
from django.shortcuts import render
from . models import Catagory, Course, Lesson
from django.db.models import Prefetch
# Create your views here.

def index(request):
  catagories = Catagory.objects.all().prefetch_related('course_set')
  context = {'catagories': catagories,}
  return render(request, 'courses/index.html', context)

def course(request, course_id):
  
  course = Course.objects.filter(pk=course_id).prefetch_related(Prefetch('lesson_set', queryset=Lesson.objects.order_by('lesson_order'))).all()
  
  context = {'course': course,}
  return render(request, 'courses/course.html', context)

def lesson(request, lesson_id):
           
  lesson = Lesson.objects.filter(pk=lesson_id).prefetch_related(Prefetch('question_set')).all()
  context = {'lesson': lesson,}
  return render(request, 'courses/lesson.html', context)

courses/templates/courses/course.html
{% extends 'base.html' %}
{% load cms_tags menu_tags sekizai_tags %}
{% load i18n %} 
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
      
      
      {% block css %}
      <style>
      
      </style>
      {% endblock css %}
      
      {% block content %}
      <main class="flex-shrink-0">
      <div class="container">
        <div class="row">
          <div class="col-12 p-3">
          
          {% if LANGUAGE_CODE == 'ar' %}
          
          {% for c in course %}
            <h1>{{c}}</h1>
            <p>يتوفر حاليا الدروس التالية في هذه الدورة:</p>
            <ul>
            {% for lesson in c.lesson_set.all %}
              <li><a href="{% url 'courses:lesson' lesson.id %}">{{lesson.name_ar}}</a></li>
            {% endfor %}
            </ul>
            
          {% endfor %}
          
          {% else %}
          
          {% for c in course %}
            <h1>{{c}}</h1>
            <p>The following lessons are available for this course:</p>
            <ul>
            {% for lesson in c.lesson_set.all %}
              <li><a href="{% url 'courses:lesson' lesson.id %}">{{lesson.name_en}}</a></li>
            {% endfor %}
            </ul>
            
          {% endfor %}
          
          {% endif%}
            
            
            {% placeholder "content" %}
          </div>
        </div>
      </div>
      </main>
      {% endblock content %}
 

courses/templates/courses/index.html
{% extends 'agency_base.html' %}
{% load cms_tags menu_tags sekizai_tags %}
{% load i18n %} 
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
      
      
      
      {% block content %}
      <div class="container">
        <div class="row">
          <div class="col-12 p-3">
          
          {% if LANGUAGE_CODE == 'ar' %}
          <h1>أهلا بكم في صفحة دروس العود</h1>
          <p>يتوفر حاليا التصنيفات التالية من الدروس:</p>
          <ul>
            {% for catagory in catagories %}
              
              <li>{{catagory.name_ar}}</li>
              
              <ul>
              {% for course in catagory.course_set.all %}
              <li><a href="{% url 'courses:course' course.id %}">{{course}}</a></li>
              {% endfor %}
              </ul>
              
            {% endfor %}
          </ul>
          
          {% else %}
          
          <h1>Welcome to the Oud Lessons</h1>
          <p>The following catagories are available:</p>
          <ul>
            {% for catagory in catagories %}
              
              <li>{{catagory.name_en}}</li>
              
              <ul>
              {% for course in catagory.course_set.all %}
              <li><a href="{% url 'courses:course' course.id %}">{{course}}</a></li>
              {% endfor %}
              </ul>
              
            {% endfor %}
          </ul>
          
          {% endif%}
            
            
            {% placeholder "content" %}
          </div>
        </div>
      </div>
      {% endblock content %}
 

courses/templates/courses/lesson.html
{% extends 'base.html' %}
{% load cms_tags menu_tags sekizai_tags %}
{% load i18n %} 
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
{% get_static_prefix as STATIC_PREFIX %}
      
      
      {% block css %}
      <style>
      .min-100 {
        min-height: 100%;
      }
      </style>
      {% endblock css %}
      {% block content %}
      <div class="container">
        <div class="row">
          <div class="col-12 p-3">
          
          {% if LANGUAGE_CODE == 'ar' %}
          
            <div class="row">
              <div class="col-12">
              {% for l in lesson %}
                <h1>{{ l.name_ar }}</h1>
                <hr>
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{%url 'courses:index'%}">{{ l.course.catagory.name_ar }}</a></li>
                    <li class="breadcrumb-item"><a href="{%url 'courses:course' l.course.id%}">{{ l.course.name_ar }}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ l.name_ar }}</li>
                  </ol>
                </nav>
                
                <h2>فيديو الشرح:</h2>
                <hr>
              </div>
            </div>
            
            <div class="row">
              <div class="col-12 embed-responsive embed-responsive-16by9">
                <iframe src="{{l.video_link}}" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen class="embed-responsive-item" title="Basic Music Theory"></iframe>
                
              </div>
            </div>
            
            <div class="row">
              <div class="col-12">
              <h2>ملاحظات إضافية:</h2>
              <hr>
              {% for obj in lesson %}
                {% render_placeholder obj.lesson_placeholder language 'ar' %}
              {% endfor %}
                
              </div>
            </div>
            
            <div class="row">
              <div class="col-12">
                <h2>اختبار قياس مدى الاستيعاب:</h2>
                <hr>
                <ul>
                {% for q in l.question_set.all %}
                  <li>{{q}}</li>
                  
                  <ol>
                  {% for a in q.answer_set.all %}
                      <li>{{ a }}</li>
                  {% endfor %}
                  </ol>
                  
                {% endfor %}
                </ul>
              </div>
            </div>
          {% endfor %}
          
          {% else %}
          
          <div class="row">
              <div class="col-12">
              {% for l in lesson %}
                <h1>{{ l.name_en }}</h1>
                <hr>
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{%url 'courses:index'%}">{{ l.course.catagory.name_en }}</a></li>
                    <li class="breadcrumb-item"><a href="{%url 'courses:course' l.course.id%}">{{ l.course.name_en }}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ l.name_en }}</li>
                  </ol>
                </nav>
                <h2>Explanatory Video:</h2>
                <hr>
              </div>
            </div>
            
            <div class="row">
              <div class="col-12 embed-responsive embed-responsive-16by9">
                <iframe src="{{l.video_link}}" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen class="embed-responsive-item" title="Basic Music Theory"></iframe>
                
              </div>
            </div>
            
            <div class="row">
              <div class="col-12">
              <h2>Extra Notes:</h2>
              <hr>
              {% for obj in lesson %}
                {% render_placeholder obj.lesson_placeholder language 'en' %}
              {% endfor %}
                
              </div>
            </div>
            
            <div class="row">
              <div class="col-12">
                <h2>Comprehension Test:</h2>
                <hr>
                <ul>
                {% for q in l.question_set.all %}
                  <li>{{q}}</li>
                  
                  <ol>
                  {% for a in q.answer_set.all %}
                      <li>{{ a }}</li>
                  {% endfor %}
                  </ol>
                  
                {% endfor %}
                </ul>
              </div>
            </div>
          {% endfor %}
          
          {% endif%}
            
            
            
          </div>
        </div>
      </div>
      <div id="comp" class="dlog">wait until soundfonts are loaded ...<br></div>
      {% endblock content %}
 


      {% block js %}
      
        <script src="{% static 'oudwithrad/js/abc2svg-1.js' %}"></script>
        <script src="{% static 'oudwithrad/js/xmlplay_emb.js' %}"></script>
      {% endblock js %}