books/urls.py
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static 
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('plain/', views.index, name='index1'),
    path('<int:book_id>/', views.book_detail, name='book_detail'),
    
    path('authors/', views.authors, name='authors_index'),
    path('author/<int:author_id>/', views.author_detail, name='author_detail'),
    path('authors/paginated_list', views.authors_paginated_list, name='authors_paginated_list'),
    
    path('genres/', views.genres, name='genres_index'),
    path('d3graph/', views.d3graph, name='d3graph'),
    path('d3graph/json_data_sender', views.json_data_sender, name='json_data_sender'),
]

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oudwithrad/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, re_path
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.views.static import serve

admin.autodiscover()

urlpatterns = i18n_patterns(
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)
#urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns = [
        #re_path(r'^filer/', include('filer.urls')),
        re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns
# note the django CMS URLs included via i18n_patterns

urlpatterns += i18n_patterns(
    
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^polls/', include('polls.urls')),
    #re_path(r'^compositions/', include('compositions.urls')),
    re_path(r'^', include('cms.urls')),
)

books/models.py
from django.db import models
from filer.fields.image import FilerImageField
from django.utils.translation import get_language
from django.utils.translation import ugettext_lazy as _
from cms.models.fields import PlaceholderField

# Create your models here.
class Author(models.Model):
    first_name_en = models.CharField(max_length=200, blank=True)
    first_name_ar = models.CharField(max_length=200, blank=True)
    last_name_en = models.CharField(max_length=200, blank=True)
    last_name_ar = models.CharField(max_length=200, blank=True)
    arabic_definite_article = models.BooleanField(default=False)
    
    def __str__(self):
        return self.first_name_en + " " + self.last_name_en

class Translator(models.Model):
    first_name_en = models.CharField(max_length=200, blank=True)
    first_name_ar = models.CharField(max_length=200, blank=True)
    last_name_en = models.CharField(max_length=200, blank=True)
    last_name_ar = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self. first_name_en + " " + self.last_name_en
      
class Publisher(models.Model):
    name_en = models.CharField(max_length=200, unique=True)
    name_ar = models.CharField(max_length=200, default='غير معروف')
    def __str__(self):
        return self.name_en 

class Genre(models.Model):
    name_en = models.CharField(max_length=200, unique=True)
    name_ar = models.CharField(max_length=200, blank=True, default='تصنيف')
    def __str__(self):
        return self.name_en
      
class Type(models.Model):
    type = models.CharField(max_length=10, unique=True)
    
    def __str__(self):
        return self.type
      
class Title(models.Model):
    LANGUAGES = (
        ('en', 'English'),
        ('fr', 'French'),
        ('de', 'German'),
        ('sr', 'Serbian'),
        ('ar', 'Arabic'),
        ('cn', 'Chinese'),
        ('sw', 'Swedish'),
        ('ak', 'Akkadian'),
        ('la', 'Latin'),
        ('es', 'Spanish'),
        ('fa', 'Persian'),
        ('el', 'Greek'),
        ('ru', 'Russian'),
        ('pt', 'Portuguese'),
        ('tr', 'Turkish'),
        ('it', 'Italian'),
    )
    cover = FilerImageField(
        verbose_name=_('Book Cover'),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='cover',
    )
    title_en = models.CharField(max_length=200, unique=True)
    title_ar = models.CharField(max_length=200, default='العنوان')
    authors = models.ManyToManyField(Author)
    genres = models.ManyToManyField(Genre, blank=True)
    translated = models.BooleanField()
    translators = models.ManyToManyField(Translator, blank=True)
    year = models.IntegerField(default=0)
    original_language = models.CharField(max_length=2, choices=LANGUAGES, blank=True)
    language = models.CharField(max_length=2, choices=LANGUAGES)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    types = models.ForeignKey(Type, on_delete=models.CASCADE)
    file = models.CharField(max_length=500, blank=True)
    def __str__(self):
        return self.title_en

books/views.py
from .models import Title, Author, Genre

from django.shortcuts import render
# Create your views here.
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render

from django.db.models import Sum, Avg
from django.db.models import Count

from os import path
from PIL import Image
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
from wordcloud import WordCloud, STOPWORDS
#from wordcloudgen.wordcloud import *
import io
import urllib, base64

import networkx as nx
import json

from functools import wraps
import time

def timer(func):
    """helper function to estimate view execution time"""

    @wraps(func)  # used for copying func metadata
    def wrapper(*args, **kwargs):
        # record start time
        start = time.time()

        # func execution
        result = func(*args, **kwargs)
        
        duration = (time.time() - start) * 1000
        # output execution time to console
        print('view {} takes {:.2f} ms'.format(
            func.__name__, 
            duration
            ))
        return result
    return wrapper


# Create your views here.

#index
@timer
def index(request):
  #Determine The order of presentation of books
  if not request.GET.get('order_by'):
      order_by = 'year'
  else:
      order_by = request.GET.get('order_by')
  
  print(order_by)
  
  #get the books
  #all_books = Title.objects.order_by(order_by)
  all_books = Title.objects.order_by(order_by).prefetch_related('authors', 'publisher' ).all
  

  authors_count = Author.objects.count()
  genres_count = Genre.objects.count()
  
  
  context = {
    'order_by': order_by,
    'all_books': all_books,
    'authors_count': authors_count,
    'genres_count': genres_count,
    }
  
  return render(request, 'books/books_index.html', context)

#book_detail
@timer
def book_detail(request, book_id):
    try:
        book = Title.objects.get(pk=book_id)
    except Title.DoesNotExist:
        raise Http404("Book does not exist")
    return render(request, 'books/book_detail.html', {'book': book,})

#authors
@timer
def authors(request):
  authors = Author.objects.prefetch_related('title_set').all
  #authors = Author.objects.order_by('last_name')
  return render(request, 'books/authors_index.html', {'authors': authors})

#author_detail
def author_detail(request, author_id):
    try:
        author = Author.objects.get(pk=author_id)
    except Author.DoesNotExist:
        raise Http404("Author does not exist")
    return render(request, 'books/author_detail.html', {'author': author})
  
#genres
@timer
def genres(request):
  genres = Genre.objects.prefetch_related('title_set', 'title_set__authors', 'title_set__publisher').all
  
  #genres = Genre.objects.order_by('name')
  titles = Title.objects.all()
  #topics_graph = books_graph(genres, titles)
  
  genres_count = Genre.objects.values("name_en").annotate(count=Count("title"))
  
  frequency_dict = {r['name_en'] : r['count'] for r in genres_count}
  
  books_wc = books_wordcloud(frequency_dict)
  return render(request, 'books/genres_index.html', {'genres': genres,
                                                     #'topics_graph': topics_graph,
                                                     'books_wordcloud': books_wc,
                                                     })

def d3graph(request):
    #initialize a variable to hold the graph
  G = nx.Graph()
  
  #Add book topics as nodes in the graph
  genres_with_titles_counts = Genre.objects.annotate(Count('title'))

  for genre in genres_with_titles_counts:
    G.add_node(genre.name, size=genre.title__count)
  
  #Add book titles as nodes
  titles = Title.objects.all() #to make the edges
  for title in titles:
    G.add_node(title.id)
    #Add edges for the topics the title is related to
    for genre in title.genres.all():
      G.add_edge(genre.name, title.id)
    
    #Clear the title node and concatate its edges
    neighbors = list(nx.neighbors(G, title.id)) #finding the neighbors of each title
    G.remove_node(title.id) #Remove the title node and its edges
    
    for neighbor in neighbors:
      remaining_ns = neighbors
      if remaining_ns: #make sure the node has neighbors
        for remaining_n in remaining_ns: #a loop to add edges
          if remaining_n != neighbor: #check that the neighbor is different than the starting node
            if G.has_edge(neighbor, remaining_n): #Check if the edge is already exsisting, add to its weight, else add edge
              G[neighbor][remaining_n]['weight'] += 1
            else:
              G.add_edge(neighbor, remaining_n, weight=1)
  data1 = nx.readwrite.json_graph.node_link_data(G)
  print(data1)
  s1 = json.dumps(data1) 
  authors = 'nafez'
  return render(request, 'books/d3graph.html', {'authors': authors,
                                                's1': s1,})

def json_data_sender(request): #helper function for d3graph to send data as json
    #initialize a variable to hold the graph
  G = nx.Graph()
  
  #Add book topics as nodes in the graph
  genres = Genre.objects.all() #representing the nodes
  for genre in genres:
    G.add_node(genre.name)
  
  #Add book titles as nodes
  titles = Title.objects.all() #to make the edges
  for title in titles:
    G.add_node(title.id)
    #Add edges for the topics the title is related to
    for genre in title.genres.all():
      G.add_edge(genre.name, title.id)
    
    #Clear the title node and concatate its edges
    neighbors = list(nx.neighbors(G, title.id)) #finding the neighbors of each title
    G.remove_node(title.id) #Remove the title node and its edges
    
    for neighbor in neighbors:
      remaining_ns = neighbors
      if remaining_ns: #make sure the node has neighbors
        for remaining_n in remaining_ns: #a loop to add edges
          if remaining_n != neighbor: #check that the neighbor is different than the starting node
            if G.has_edge(neighbor, remaining_n): #Check if the edge is already exsisting, add to its weight, else add edge
              G[neighbor][remaining_n]['weight'] += 1
            else:
              G.add_edge(neighbor, remaining_n, weight=1)
  data1 = nx.readwrite.json_graph.node_link_data(G)
  s1 = json.dumps(data1) 
  return JsonResponse(list(s1), safe=False)

def books_graph(genres, titles):
  #a function that returns a png image of the graph of movie genres
  G = nx.Graph()
  
  #genres = Genre.objects.all() #representing the nodes
  for genre in genres:
    G.add_node(genre)
    
  #titles = Title.objects.all() #to make the edges
  for title in titles:
    G.add_node(title.id)
    for genre in title.genres.all():
      G.add_edge(genre, title.id)
    neighbors = list(nx.neighbors(G, title.id))
    #print(neighbors)
    G.remove_node(title.id)
    for neighbor in neighbors:
      #remaining_ns = neighbors.remove(neighbor)
      remaining_ns = neighbors
      print(remaining_ns)
      if remaining_ns:
        for remaining_n in remaining_ns:
          if remaining_n != neighbor:
            if G.has_edge(neighbor, remaining_n):
              G[neighbor][remaining_n]['weight'] += 1
            else:
              G.add_edge(neighbor, remaining_n, weight=1)
              
  pos = nx.spring_layout(G)
  __location__ = os.path.realpath(
                    os.path.join(os.getcwd(), os.path.dirname(__file__)))
  font_path = path.join(__location__, "AvenirArabic_Regular.otf")
  
  options = {
    'font_path': font_path,
    'pos': pos,
    'node_color': 'lightgreen', 
    'node_size': 100,
    'with_labels': True,
    'linewidths': 0,
    'width': 0.1,
    }
  
  nx.draw(G, **options)
  
  ''' To create custom labls uncomment the following section:
  edge_labels = nx.get_edge_attributes(G,'weight')
  custom_node_attrs = {}
  for node, attr in edge_labels.items():
    custom_node_attrs[node] = attr
  '''
  
  for edge in G.edges(data='weight'):
    nx.draw_networkx_edges(G, pos, edgelist=[edge], width=edge[2]/5)
    #connectionstyle'arc3, rad=0.2'
  #to draw custom labels uncomment the following line:
  #nx.draw_networkx_edge_labels(G, pos, edge_labels = custom_node_attrs)

  fig = plt.gcf()
  buf = io.BytesIO()
  fig.savefig(buf, format='png')
  buf.seek(0)
  string = base64.b64encode(buf.read())
  plt.close() 
  image_uri = 'data:image/png;base64,' + urllib.parse.quote(string)
  return image_uri

from django.contrib.staticfiles import finders
@timer
def books_wordcloud(frequency_dict):
    '''
    text = ""
    #genres = Genre.objects.order_by('genre_name')
    for genre in genres:
      books_count = Title.objects.filter(genres=genre).count()
      i = 0
      while i < int(books_count):
        text += str(genre)
        text += " "
        i += 1
    
    processed_text = text.lower().split()
    text_dict = {}
    for item in processed_text:
        text_dict[item] = item.count(item)
    '''
    
    #Getting the font file
    #__location__ = os.path.realpath(
                  #os.path.join(os.getcwd(), os.path.dirname(__file__)))
    #font_path = path.join(__location__, "AvenirArabic_Regular.otf")
    font_path = finders.find('oudwithrad/DubaiWebFont/webfonts/DubaiW23-Bold.ttf')
    #font_path = static('oudwithrad/DubaiWebFont/webfonts/DubaiW23-Regular.ttf')
    print(font_path)
    #Creating a circular mask
    x, y = np.ogrid[:300, :300]
    mask = (x - 150) ** 2 + (y - 150) ** 2 > 130 ** 2
    mask = 255 * mask.astype(int)
    
    wc = WordCloud(scale=10, max_words=100, mask=mask, font_path=font_path, colormap="tab20", background_color="#fff", repeat=False).generate_from_frequencies(frequency_dict)
    plt.figure(figsize=(4,4))
    plt.subplots_adjust(top = 1, bottom = 0, right = 1, left = 0, 
            hspace = 0, wspace = 0)
    plt.axis("off")
    plt.margins(0,0)
    plt.imshow(wc, interpolation="bilinear", aspect='auto')
    fig = plt.gcf()
    buf = io.BytesIO()
    fig.savefig(buf, format='png')
    buf.seek(0)

books/templates/books/authors_index.html
{% extends "base.html" %}
{% load mathfilters %}
{% load humanize %}
{% load arabic_numbers %}
{% load i18n %} 
{% get_current_language as LANGUAGE_CODE %}

{% block css%}
<style>
.rtl_item {
  text-align: right;
}


.books_count {
  font-size: 18px;
  font-weight: 300;
  color: black;
  vertical-align: middle;
  }
.author_books_list {
  font-family: 'Apercu Arabic Pro';
  font-size: 15px;
  font-weight: 400;
  }
</style>


{% endblock %}
{% block title %}NafColl Books{% endblock %}


  <!-- Navigation -->

  <!-- Page Content -->

  {% block content %}
  {% if LANGUAGE_CODE == 'ar' %}
  
  <div class="container">
    <div class="row">
      <div class="col-12 p-3">
      
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">الرئيسية</a></li>
            <li class="breadcrumb-item"><a href="{%url 'books:index' %}">الكتب</a></li>
            <li class="breadcrumb-item active" aria-current="page">المؤلفون</li>
          </ol>
        </nav>
        
        <hr>
        
        <h1 class="text-center">مرحبـــــا بـــــكم فـــــي قائمة المؤلفين</h1>
        
        <hr>
        
        <p class="text-center">There are {{authors.count}} authors in the database<br>يوجد {{authors.count}} مؤلف في قاعدة البيانات</p>
        
        <p class="text-center">Go to <a href="{% url 'books:genres_index' %}">TOPICS</a></p>
        
        <hr>
  
        {% for author in authors %}
        {% with author.title_set.all|first as first_object %}
    
        <!--Arabic Authors Heading -->
          
          <h2>
          {{author.first_name_ar }} {% if author.arabic_definite_article %}ال{%endif%}{{ author.last_name_ar }}
        
            {% if author.title_set.count == 1 %}
            <span class="books_count">
          (كتاب واحد)
            </span></h2>
            {% elif author.title_set.count == 2 %}
            <span class="books_count">
          (كتابين)
            </span></h2>
            {% else %}
            <span class="books_count">
            ({{ author.title_set.count|enToArNumb }} كتب)
            </span></h2>
            {% endif %} <!--end of Arabic plural endings-->
          
        
        {% endwith %}
    
          <ul class="author_books_list">
          {% for book in author.title_set.all|dictsort:"year" %}
          
            
              <li>
                <a class=bookTitle href={% url 'books:book_detail' book.id %}>
                {{ book.title_ar }}</a> ({{book.year|enToArNumb}}){% if book.translated %}، مترجم من {{ book.original_language }}.{% endif %}
              </li>
            
            
          
          {% endfor %}
          </ul>
    
        {% endfor %}
        
      </div>
    </div>
  </div>     <!-- end Arabic template container -->
  
  {% else %} <!--   start of english template   -->
  
  <div class="container">
    <div class="row">
      <div class="col-12 p-3">
      
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">HOME</a></li>
            <li class="breadcrumb-item"><a href="{%url 'books:index' %}">BOOKS</a></li>
            <li class="breadcrumb-item active" aria-current="page">AUTHORS</li>
          </ol>
        </nav>
        
        <hr>
        
        <h1 class="text-center"> Welcome to the Authors List</h1>
        
        <hr>
        
        <p class="text-center">There are {{authors.count}} authors in the database.</p>
        
        <p class="text-center">Go to <a href="{% url 'books:genres_index' %}">TOPICS</a></p>
        <hr>
  
        {% for author in authors %}
        {% with author.title_set.all|first as first_object %}
          
        <h2>{{ author.last_name_en }}{% if author.name == 'Anonymous' %}{% elif author.name == '.' %}{% else %}, {{ author.first_name_en }} {% endif %}
        
          {% if author.title_set.count == 1 %}
            <span class="books_count">({{ author.title_set.count }} title)</span></h2>
            {% else %}
            <span class="books_count">({{ author.title_set.count }} titles)</span></h2>
          {% endif %}
          
        {% endwith %}
    
        <ul class="author_books_list">
          
        {% for book in author.title_set.all|dictsort:"year" %}
            
          <li>
            <a class=bookTitle href={% url 'books:book_detail' book.id %}>
              {{ book.title_en }}
            </a> ({{ book.year }}){% if book.translated %}, transtaled from {{ book.original_language }}.{% endif %}
            </li>
              
          {% endfor %}
          </ul>
    
        {% endfor %}
        
      </div>
    </div>
  </div>
  
  {% endif %}
  
  
  
  {% endblock %}

books/templates/books/book_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load i18n %} 
{% get_current_language as LANGUAGE_CODE %}

{% block content %}

{% if LANGUAGE_CODE == 'ar' %}
<div class="container">
    <div class="row">
      <div class="col-12 p-3">
        
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">الرئيسية</a></li>
            <li class="breadcrumb-item"><a href="{%url 'books:index' %}">الكتب</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ book.title_ar }}</li>
          </ol>
        </nav>
        
        <hr>
                
        <h1>{{ book.title_ar }}</h1>
    
        <h3>تأليف: 
        
        {% for author in book.authors.all %}
        
          {% if not forloop.last %}
            {{ author.first_name_ar }} {{author.last_name_ar }}،
          {% else %}
            {{ author.first_name_ar }} {{author.last_name_ar }}.
          {% endif %}
          
        {% endfor %}
        </h3>
        
        
        

        صنف تحت: | {% for genre in book.genres.all %}
          {{ genre.name_ar }} | 
        {% endfor %} <br>
    
        {% if book.cover %}
        <img src="{% thumbnail book.cover 300x400 crop %}"><br>
        {% else %}
        لا يوجد صورة لهذا الكتاب.
        {% endif %}

    
        <p>نشر في سنة {{ book.year }} من قبل {{ book.publisher.name_ar }}.</p>

        <p>اللغة: <b>{{ book.language|upper }}</b>.
        {% if book.translated %}
        Translated from {{ book.original_language|upper}}, by: 
        {% for translator in book.translators.all %}
          {{ translator }} | 
        {% endfor %}
        {% endif %}
        </p>
    
        <p>
        اسم الملف: {{ book.file }}</a>
        </p>
    
      </div>
    </div>
  </div>
{% else %}
  <div class="container">
    <div class="row">
      <div class="col-12 p-3">
        
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">HOME</a></li>
            <li class="breadcrumb-item"><a href="{%url 'books:index' %}">Books</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ book.title_en }}</li>
          </ol>
        </nav>
        
        <hr>
                
        <h1>{{ book.title_en }}</h1>
    
        <h3>Wirtten by: 
        
        {% for author in book.authors.all %}
        
          {% if not forloop.last %}
            {{ author.first_name_en }} {{author.last_name_en }},
          {% else %}
            {{ author.first_name_en }} {{author.last_name_en }}.
          {% endif %}
          
        {% endfor %}
        </h3>
        
        
        

        Filed under: | {% for genre in book.genres.all %}
          {{ genre.name_en }} | 
        {% endfor %} <br>
    
        {% if book.cover %}
        <img src="{% thumbnail book.cover 300x400 crop %}"><br>
        {% else %}
        No cover is added.
        {% endif %}

    
        <p>Published in {{ book.year }} by {{ book.publisher.name_en }}.</p>

        <p>Language <b>{{ book.language|upper }}</b>.
        {% if book.translated %}
        Translated from {{ book.original_language|upper}}, by: 
        {% for translator in book.translators.all %}
          {{ translator }} | 
        {% endfor %}
        {% endif %}
        </p>
    
        <p>
        file name: {{ book.file }}</a>
        </p>
    
      </div>
    </div>
  </div>
{% endif %}
{% endblock content %}

books/templates/books/books_index.html
{% extends "base.html" %}
{% load mathfilters %}
{% load arabic_numbers %}
{% load humanize %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block css %}
<style>

  {% if LANGUAGE_CODE == 'ar' %}
  
  ol {list-style-type: arabic-indic; !important}
  
  {% endif %}
  
</style>
{% endblock css %}

{% block title %}NafColl Books{% endblock %}


  <!-- Navigation -->

  <!-- Page Content -->

  {% block content %}
  
  {% if LANGUAGE_CODE == 'ar' %}
  
  <div class="container">
    <div class="row">
      <div class="col-12 p-3">
        <h1 class="text-center">أهلا بكم في مجموعة الكتب</h1>
        
        <hr style="max-width:650px" class="mx-auto">
        
        <p class="text-center">يوجد حاليا {{ all_books.count|enToArNumb }} كتب في قاعدة البيانات, 
        من قبل {{ authors_count|enToArNumb }} <a href="{% url 'books:authors_index' %}">كاتبا</a>، موزعة على {{ genres_count|enToArNumb }} <a href="{% url 'books:genres_index' %}">تصنيف</a>.</p>
        
        <p class="text-center">قائمة الكتب مرتبة بحسب
        {% if order_by == 'year' %}
          سنة الطباعة.<br>
        {% else %}
          عنوان الكتاب<br>
        {% endif %}
        قم بترتيب الكتب بحسب: <a href="{% url 'books:index' %}?order_by=year">سنة الطباعة</a> أو بحسب 
        <a href="{% url 'books:index' %}?order_by=title_en">العنوان</a>.</p>
        
        <hr style="max-width:650px" class="mx-auto">
      </div>
    </div>
    
    <div class="row">
      <div class="col-12">
      
        <ol>
        {% for book in all_books %}
          
          <li>
            <a class=bookTitle href="{% url 'books:book_detail' book.id %}">
              <strong>{{ book.title_ar }}</strong>
            </a>
        
            {% if user.is_superuser %}<a class="mgt_links" href="/admin/books/title/{{ book.id }}/change/">(تعديل)</a>{% endif %}<br>
      
            <span class='book_detail'>
            
            {% for author in book.authors.all %}
            
              {% if not forloop.last %}
                {{ author.first_name_ar }} {% if author.arabic_definite_article %}ال{%endif%}{{ author.last_name_ar }} و
              {% else %}
                  {{ author.first_name_ar }} {% if author.arabic_definite_article %}ال{%endif%}{{ author.last_name_ar }}،
              {% endif %}
              
            {% endfor %}
          
            {{ book.publisher.name_ar }} <strong>[{{book.year|enToArNumb}}]</strong>
            </span>
          </li>
      
        {% endfor %}
        </ol>
      
      </div>
    </div>
    
  </div><!--end of container-->
  
  {% else %}
  
  <div class="container">
  
    <div class="row">
      <div class="col-12 p-3">
        <h1 class="text-center">Welcome to the Books Collection</h1>
        
        <hr style="max-width:650px" class="mx-auto">
        
        <p class="text-center">There are {{ all_books.count }} books in the database, 
        from {{ authors_count }} <a href="{% url 'books:authors_index' %}">authors</a>, covering {{ genres_count }} <a href="{% url 'books:genres_index' %}">topics</a>.</p>
        
        <p class="text-center">The displayed books list is ordered by 
        {% if order_by == 'year' %}
          publication {{order_by}}.<br>
        {% else %}
          {{ order_by }}.<br>
        {% endif %}
        Order the books by: <a href="{% url 'books:index' %}?order_by=year">year</a> or by 
        <a href="{% url 'books:index' %}?order_by=title_en">title</a>.</p>
        
        <hr style="max-width:650px" class="mx-auto">
      </div>
    </div>
    
    <div class="row">
      <div class="col-12">
      
        <ol>
        {% for book in all_books %}
    
          <li>
            <a class=bookTitle href="{% url 'books:book_detail' book.id %}">
              <strong>{{ book.title_en }}</strong>
            </a>
          
            {% if user.is_superuser %}<a class="mgt_links" href="/admin/books/title/{{ book.id }}/change/">(edit)</a>{% endif %}<br>
      
            <span class='book_detail'>
            {% for author in book.authors.all %}
              {% if not forloop.last %}
                {{ author.first_name_en }} {{ author.last_name_en }},
              {% else %}
                {{ author.first_name_en }} {{ author.last_name_en }}.
              {% endif %}
            {% endfor %}
          
            {{ book.publisher }} <strong>[{{ book.year }}]</strong>
            </span>
          </li>
          
        {% endfor %}
        </ol>
      
      </div>
    </div>
    
  </div>
  
  {% endif %}
  
  
  {% endblock %}